### ISSUE TITLE
Crashes server

### ISSUE THREAD

**Issue by smcardle** [nabbl/node-red-contrib-tcp-ping#3]
This just crashes my NodeRED server

I have no idea what to put in the fields and you have provided no documentation that gets installed with the node

**Comment by MrBlue90** [comment]
Same here. Took em a few hours to recover everything.
Apparently fails at the following exception:
```
22 Aug 10:59:07 - [red] Uncaught Exception:
22 Aug 10:59:07 - RangeError [ERR_OUT_OF_RANGE]: The value of "msecs" is out of range. It must be a non-negative finite number. Received NaN
    at getTimerDuration (internal/timers.js:383:11)
    at Socket.setStreamTimeout [as setTimeout] (internal/stream_base_commons.js:250:11)
    at Tcpie.start (/root/.node-red/node_modules/tcpie/index.js:45:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by fah** [comment]
I left the port empty and got an equal message. 
```
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN. 
 at validatePort (internal/validators.js:182:11) 
 at lookupAndConnect (net.js:1002:5) 
 at Socket.connect (net.js:978:5) 
 at Tcpie.start (/opt/iobroker/iobroker-data/node-red/node_modules/tcpie/index.js:68:16) 
 at listOnTimeout (internal/timers.js:554:17) 
 at processTimers (internal/timers.js:497:7)
```

Question here is: Why are good defaults not set instead of letting the server crash.

Then when entering everyting into payload, ping got a 
```
ECONNREFUSED 192.168.1.1:7
```

And this host is definitely available.
